name: 'Anchor Verifiable Build'
description: 'Generate a verifiable Anchor build'
inputs:
  program:
    description: 'The program name'
    required: true
  anchor-version:
    description: 'Version of Anchor to use'
    required: true
  solana-cli-version:
    description: 'Version of Solana to use'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: metadaoproject/setup-anchor@v2
      with:
        anchor-version: ${{ inputs.anchor-version }}
        solana-cli-version: ${{ inputs.solana-cli-version }}
    - name: Cache Cargo registry + index
      uses: actions/cache@v2
      id: cache-cargo-registry
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: cargo-${{ runner.os }}-v0001-${{ hashFiles('**/Cargo.lock') }}
    - name: Cache Solana Verify
      uses: actions/cache@v2
      id: cache-solana-verify
      with:
        path: |
          ~/.cargo/bin/solana-verify
        key: cargo-${{ runner.os }}-solana-verify
    - run: cargo install solana-verify
      if: steps.cache-solana-verify.outputs.cache-hit != 'true'
      shell: bash
    - run: ~/.cargo/bin/solana-verify build --library-name $PROGRAM --base-image ellipsislabs/solana:${{ inputs.solana-cli-version }}
      shell: bash
      env:
        PROGRAM: ${{ inputs.program }}
